POST http://localhost:8080/students
Content-Type: application/json

{
  "name": "Мария",
  "age": 19
}

###
GET http://localhost:8080/students/1

###
PUT http://localhost:8080/students/1
Content-Type: application/json

{
  "name": "Василий",
  "age": 21
}

###
DELETE http://localhost:8080/students/1

###
GET http://localhost:8080/students?age=19

###
PATCH http://localhost:8080/students/1/avatar
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="avatar"; filename="avatar.png"
Content-Type: image/png

< avatar.png
--WebAppBoundary

###
GET http://localhost:8080/students/lastStudents

###
GET http://localhost:8080/avatars

###
GET http://localhost:8080/getPort
